name: Deploy Project

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.x'

    - name: Restore .NET dependencies
      run: dotnet restore

    - name: Build Blazor App
      run: dotnet publish -c Release -o build_output

   
    - name: Assume role and configure AWS credentials
      id: aws-credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: LabRole
        aws-region: us-east-1
        role-session-name: github-actions
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        role-skip-session-tagging: true
        
    - name: Deploy Blazor App to S3
      run: |
        aws s3 sync build_output/wwwroot s3://seng4400-clicker-frontend --delete
