name: Deploy Project

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.x'

    - name: Restore .NET dependencies
      run: dotnet restore

    - name: Build Blazor App
      run: dotnet publish Frontend/Frontend.csproj -c Release -o build_output

    - name: Build Lambda - Post to Dynamo
      run: dotnet publish PostToDynamo/PostToDynamo.csproj -c Release -r linux-x64 -o lambda_build_output_post_to_dynamo

    - name: Build Lambda - Process Leaderboard
      run: dotnet publish GetLeaderboard/GetLeaderboard.csproj -c Release -r linux-x64 -o lambda_build_output_process_leaderboard
      
    - name: Package Lambda - Post to Dynamo
      run: |
        cd lambda_build_output_post_to_dynamo
        zip -r ../lambda_function_post_to_dynamo.zip .
        cd ..

    - name: Package Lambda - Process Leaderboard
      run: |
        cd lambda_build_output_process_leaderboard
        zip -r ../lambda_function_process_leaderboard.zip .
        cd ..
   
    - name: Configure AWS credentials
      id: aws-credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: us-east-1
        role-session-name: github-actions
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        
    - name: Deploy Blazor App to S3
      run: |
        aws s3 sync build_output/wwwroot s3://seng4400-clicker-frontend --delete


    - name: Deploy Lambda - Post to Dynamo
      run: |
        aws lambda update-function-code --function-name Lambda1 --zip-file fileb://lambda_function_post_to_dynamo.zip

    - name: Deploy Lambda - Process Leaderboard
      run: |
        aws lambda update-function-code --function-name ProcessLeaderboard --zip-file fileb://lambda_function_process_leaderboard.zip


